/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedLeagueIdRouteImport } from './routes/_authenticated/league.$id'
import { Route as AuthenticatedLeagueIdDraftRouteImport } from './routes/_authenticated/league.$id.draft'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeagueIdRoute = AuthenticatedLeagueIdRouteImport.update({
  id: '/league/$id',
  path: '/league/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeagueIdDraftRoute =
  AuthenticatedLeagueIdDraftRouteImport.update({
    id: '/draft',
    path: '/draft',
    getParentRoute: () => AuthenticatedLeagueIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/league/$id': typeof AuthenticatedLeagueIdRouteWithChildren
  '/league/$id/draft': typeof AuthenticatedLeagueIdDraftRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/': typeof AuthenticatedIndexRoute
  '/league/$id': typeof AuthenticatedLeagueIdRouteWithChildren
  '/league/$id/draft': typeof AuthenticatedLeagueIdDraftRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/league/$id': typeof AuthenticatedLeagueIdRouteWithChildren
  '/_authenticated/league/$id/draft': typeof AuthenticatedLeagueIdDraftRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/admin' | '/league/$id' | '/league/$id/draft'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/admin' | '/' | '/league/$id' | '/league/$id/draft'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/'
    | '/_authenticated/league/$id'
    | '/_authenticated/league/$id/draft'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/league/$id': {
      id: '/_authenticated/league/$id'
      path: '/league/$id'
      fullPath: '/league/$id'
      preLoaderRoute: typeof AuthenticatedLeagueIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/league/$id/draft': {
      id: '/_authenticated/league/$id/draft'
      path: '/draft'
      fullPath: '/league/$id/draft'
      preLoaderRoute: typeof AuthenticatedLeagueIdDraftRouteImport
      parentRoute: typeof AuthenticatedLeagueIdRoute
    }
  }
}

interface AuthenticatedLeagueIdRouteChildren {
  AuthenticatedLeagueIdDraftRoute: typeof AuthenticatedLeagueIdDraftRoute
}

const AuthenticatedLeagueIdRouteChildren: AuthenticatedLeagueIdRouteChildren = {
  AuthenticatedLeagueIdDraftRoute: AuthenticatedLeagueIdDraftRoute,
}

const AuthenticatedLeagueIdRouteWithChildren =
  AuthenticatedLeagueIdRoute._addFileChildren(
    AuthenticatedLeagueIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLeagueIdRoute: typeof AuthenticatedLeagueIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLeagueIdRoute: AuthenticatedLeagueIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
